persistence false
log_dest file /home/hp/Documents/zachary-git/Project-1/.mqtt_server/mosquitto.log
log_type all
connection_messages true

listener 8883 0.0.0.0
allow_anonymous true

listener 1883 127.0.0.1
allow_anonymous true
